import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://curiosta.com/');
  await page.getByRole('link', { name: 'Products', exact: true }).click();
  await page.getByPlaceholder('Search products...').click();
  await page.getByPlaceholder('Search products...').fill('');
  await page.getByRole('checkbox', { name: 'Protocol Interfaces' }).check();
  await page.getByRole('checkbox', { name: 'Protocol Interfaces' }).uncheck();
  await page.getByRole('checkbox', { name: 'KiCad' }).check();
  await page.getByRole('checkbox', { name: 'KiCad' }).uncheck();
  await page.getByRole('checkbox', { name: 'Debuggers' }).check();
  await page.getByRole('checkbox', { name: 'Debuggers' }).uncheck();
  await page.getByRole('checkbox', { name: 'Wi-Fi' }).check();
  await page.getByRole('checkbox', { name: 'Wi-Fi' }).uncheck();
  await page.getByRole('checkbox', { name: 'Robotics & Motors' }).check();
  await page.getByRole('checkbox', { name: 'Robotics & Motors' }).uncheck();
  await page.getByRole('checkbox', { name: 'Microcontroller Boards' }).check();
  await page.getByRole('checkbox', { name: 'Microcontroller Boards' }).uncheck();
  await page.getByRole('checkbox', { name: 'Security & Privacy' }).check();
  await page.getByRole('checkbox', { name: 'Security & Privacy' }).uncheck();
  await page.getByRole('checkbox', { name: 'Cellular' }).check();
  await page.getByRole('checkbox', { name: 'Cellular' }).uncheck();
  await page.getByRole('checkbox', { name: 'Test Equipment' }).check();
  await page.getByRole('checkbox', { name: 'Test Equipment' }).uncheck();
  await page.getByRole('checkbox', { name: 'Environmental Sensing' }).check();
  await page.getByRole('checkbox', { name: 'Environmental Sensing' }).uncheck();
  await page.getByRole('checkbox', { name: 'Arduino' }).check();
  await page.getByRole('checkbox', { name: 'Arduino' }).uncheck();
  await page.getByRole('checkbox', { name: 'Sub-GHz' }).check();
  await page.getByRole('checkbox', { name: 'Sub-GHz' }).uncheck();
  await page.getByRole('checkbox', { name: 'GNSS' }).check();
  await page.getByRole('checkbox', { name: 'GNSS' }).uncheck();
  await page.getByRole('checkbox', { name: 'LoRa' }).check();
  await page.getByRole('checkbox', { name: 'LoRa' }).uncheck();
  await page.getByRole('checkbox', { name: 'Home Automation' }).check();
  await page.getByRole('checkbox', { name: 'Home Automation' }).uncheck();
  await page.getByRole('checkbox', { name: '*omu' }).check();
  await page.getByRole('checkbox', { name: '*omu' }).uncheck();
  await page.getByRole('checkbox', { name: 'Staff Picks' }).check();
  await page.getByRole('checkbox', { name: 'Staff Picks' }).uncheck();
  await page.getByRole('checkbox', { name: 'Bluetooth' }).check();
  await page.getByRole('checkbox', { name: 'Bluetooth' }).uncheck();
  await page.getByRole('checkbox', { name: 'Wearable' }).check();
  await page.getByRole('checkbox', { name: 'Wearable' }).uncheck();
  await page.getByRole('checkbox', { name: 'E-Paper' }).check();
  await page.getByRole('checkbox', { name: 'E-Paper' }).uncheck();
  await page.getByRole('checkbox', { name: 'Mobile Devices' }).check();
  await page.getByRole('checkbox', { name: 'Mobile Devices' }).uncheck();
  await page.getByRole('checkbox', { name: 'ARM' }).check();
  await page.getByRole('checkbox', { name: 'ARM' }).uncheck();
  await page.getByRole('combobox').selectOption('55');
  await page.getByRole('combobox').selectOption('102');
  await page.getByRole('combobox').selectOption('236');
  await page.getByRole('button', { name: 'Sort' }).click();
  await page.getByRole('button', { name: 'Price: High to Low' }).click();
  await page.getByRole('button', { name: 'Price: Low to High' }).click();
  await page.getByRole('link', { name: 'easySwitchBox easySwitchBox Introducing the easySwitchBox ... $20.00' }).click();
  await page.getByRole('combobox').selectOption('102');
  await page.getByRole('tab', { name: 'Angled view easySwitchBox' }).nth(1).click();
  await page.getByRole('tab', { name: 'Angled view easySwitchBox' }).nth(2).click();
  await page.getByRole('button', { name: 'Add to cart' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('2');
  await page.locator('div').filter({ hasText: /^Remove$/ }).click();
  await page.getByText('Continue Shopping').click();
  await page.getByRole('button', { name: 'Add to cart' }).click();
  await page.getByRole('button', { name: 'Remove' }).click();
  await page.getByRole('button', { name: 'Start Shopping' }).click();
  await page.getByRole('link', { name: 'Facebook' }).click();
  await page.goto('https://curiosta.com/products/easy-switch-box');
  await page.getByRole('link', { name: 'Instagram' }).click();
  await page.goto('https://curiosta.com/products/easy-switch-box');
  await page.getByRole('link', { name: 'Twitter' }).click();
  await page.goto('https://curiosta.com/products/easy-switch-box');
  await page.getByRole('link', { name: 'GitHub' }).click();
  await page.goto('https://curiosta.com/products/easy-switch-box');
  await page.getByRole('link', { name: 'YouTube' }).click();
  await page.goto('https://curiosta.com/products/easy-switch-box');
  await page.getByRole('link', { name: 'About Us' }).click();
  await page.getByRole('link', { name: 'Contact Us' }).click();
  await page.getByRole('link', { name: 'Terms of use' }).click();
  await page.getByRole('link', { name: 'Privacy Policy' }).click();
  await page.getByRole('link', { name: 'Shipping policy' }).click();
  await page.getByRole('link', { name: 'Return policy' }).click();
  await page.getByRole('link', { name: 'Products' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Previous' }).click();
  await page.getByRole('link', { name: 'Curiosta' }).click();
});