const countriesMap = {
  'in': 'India',
  'us': "United States",
  'gb': 'United Kingdom',
  'fr': 'France',
  'de': 'Germany',
  'es': 'Spain',
  'it': 'Italy',
  'pl': 'Poland',
  'ro': 'Romania',
  'nl': 'Netherlands',
  'be': 'Belgium',
  'gr': 'Greece',
  'pt': 'Portugal',
  'cz': 'Czech Republic',
  'hu': 'Hungary',
  'se': 'Sweden',
  'at': 'Austria',
  'bg': 'Bulgaria',
  'dk': 'Denmark',
  'fi': 'Finland',
  'sk': 'Slovakia',
  'ie': 'Ireland',
  'hr': 'Croatia',
  'lt': 'Lithuania',
  'si': 'Slovenia',
  'lv': 'Latvia',
  'ee': 'Estonia',
  'cy': 'Cyprus',
}

export default countriesMap